# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './set_conn_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(330, 250))
        Dialog.setMaximumSize(QtCore.QSize(330, 250))
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 41, 223, 138))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.lblHost = QtWidgets.QLabel(self.layoutWidget)
        self.lblHost.setObjectName("lblHost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblHost)
        self.lineHost = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineHost.setFont(font)
        self.lineHost.setObjectName("lineHost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineHost)
        self.lblDatabase = QtWidgets.QLabel(self.layoutWidget)
        self.lblDatabase.setObjectName("lblDatabase")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblDatabase)
        self.lineDatabase = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineDatabase.setFont(font)
        self.lineDatabase.setObjectName("lineDatabase")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineDatabase)
        self.lblUserName = QtWidgets.QLabel(self.layoutWidget)
        self.lblUserName.setObjectName("lblUserName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblUserName)
        self.lineUserName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineUserName.setObjectName("lineUserName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineUserName)
        self.lblPassword = QtWidgets.QLabel(self.layoutWidget)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.linePassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword.setObjectName("linePassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.linePassword)
        self.lblConnectedIcon = QtWidgets.QLabel(Dialog)
        self.lblConnectedIcon.setGeometry(QtCore.QRect(260, 60, 54, 41))
        self.lblConnectedIcon.setText("")
        self.lblConnectedIcon.setPixmap(QtGui.QPixmap("../../../../../../../home/mint183/Documents/icons/ic_sync_black_24dp/ios/ic_sync.imageset/ic_sync_2x.png"))
        self.lblConnectedIcon.setObjectName("lblConnectedIcon")
        self.lblNotConnectedIcon = QtWidgets.QLabel(Dialog)
        self.lblNotConnectedIcon.setGeometry(QtCore.QRect(260, 60, 51, 31))
        self.lblNotConnectedIcon.setText("")
        self.lblNotConnectedIcon.setPixmap(QtGui.QPixmap("../../../../../../../home/mint183/Documents/icons/ic_sync_disabled_black_24dp/ios/ic_sync_disabled.imageset/ic_sync_disabled_2x.png"))
        self.lblNotConnectedIcon.setObjectName("lblNotConnectedIcon")
        self.btnPasswordShow = QtWidgets.QPushButton(Dialog)
        self.btnPasswordShow.setGeometry(QtCore.QRect(250, 140, 31, 27))
        self.btnPasswordShow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../home/mint183/Documents/icons/ic_remove_red_eye_black_24dp/ios/ic_remove_red_eye.imageset/ic_remove_red_eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPasswordShow.setIcon(icon)
        self.btnPasswordShow.setObjectName("btnPasswordShow")
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setGeometry(QtCore.QRect(22, 192, 85, 27))
        self.btnClose.setObjectName("btnClose")
        self.btnConnect = QtWidgets.QPushButton(Dialog)
        self.btnConnect.setGeometry(QtCore.QRect(113, 192, 131, 27))
        self.btnConnect.setObjectName("btnConnect")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Postgres Connection"))
        self.lblHost.setText(_translate("Dialog", "Host"))
        self.lblDatabase.setText(_translate("Dialog", "Database"))
        self.lblUserName.setText(_translate("Dialog", "User name"))
        self.lblPassword.setText(_translate("Dialog", "Password"))
        self.btnClose.setText(_translate("Dialog", "Close"))
        self.btnConnect.setText(_translate("Dialog", "Connect && Save"))

